import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "@/lib/utils";
export const Card = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn("card", className), ...props })));
Card.displayName = "Card";
export const CardHeader = ({ className, ...props }) => (_jsx("div", { className: cn("px-5 pt-5 pb-3 flex items-start justify-between gap-4", className), ...props }));
export const CardTitle = ({ className, ...props }) => (_jsx("h3", { className: cn("text-base font-semibold tracking-tight text-foreground", className), ...props }));
export const CardDescription = ({ className, ...props }) => (_jsx("p", { className: cn("text-xs text-muted-foreground mt-0.5", className), ...props }));
export const CardContent = ({ className, ...props }) => (_jsx("div", { className: cn("px-5 pb-5", className), ...props }));
export const CardFooter = ({ className, ...props }) => (_jsx("div", { className: cn("px-5 pb-5 pt-0 flex items-center gap-2", className), ...props }));
